Improved parsing of server list

diff --git a/fastIPvanish b/fastIPvanish
--- a/fastIPvanish
+++ b/fastIPvanish
@@ -61,7 +61,7 @@ version() {
 # optional arguments for (1) Description and (2) Error code
 error_exit()
 {
-    echo "$(basename $0): ${1:-"Unknown Error"}" 1>&2
+    echo -e "$(basename $0): ${1:-"Unknown Error"}" 1>&2
     exit ${2:-1}
 }
 
@@ -205,7 +205,7 @@ parse_arguments() {
                 version
                 ;;
             -*)
-                error_exit "Option '$1' is not valid.\nTry '$0 --help for more information."
+                error_exit "Invalid option '$1'\nTry '--help' for more information."
                 ;;
             *)
                 opt_filter=$1
@@ -302,7 +302,7 @@ update_server_list() {
             delete_file $vpn_server_list
             # Read and parse results from the temp file
             while IFS='' read -r line || [[ -n "$line" ]] ; do
-                awk -F'"' '/ipvanish/{print substr($6, 10, length($6)-14)}' $list \
+                awk -F'"' '/ipvanish-/{print substr($6, 10, length($6)-14)}' $list \
                     >> "$vpn_server_list"
             done < "$temp_file"
             echo " Done";
